In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print(pd.__version__)

2.2.2

In [ ]:
ser = pd.Series([1,3,5,7,9])
ser

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
ser.values

array([1, 3, 5, 7, 9])

In [ ]:
import numpy as np
import pandas as pd

data = np.random.randint(0, 10, 4)  # index 길이와 맞춰서 4개 생성
index = ['a', 'b', 'c', 'd']

s = pd.Series(data=data, index=index, name='series_from_ndarray')
print(s)

a    7
b    3
c    5
d    1
Name: series_from_ndarray, dtype: int64

In [ ]:
s['a']

np.int64(7)

In [ ]:
data = {'서울':70000,'부산':52000,'대전':35000,'광주':40000,'제주도':28000}
s = pd.Series(data=data,name='series_from_dict')
print(s)

서울     70000
부산     52000
대전     35000
광주     40000
제주도    28000
Name: series_from_dict, dtype: int64

In [ ]:
city = ['광주','대전','부산','서울','울릉도']
s = pd.Series(data=data,index=city,name='Series_from_dict')
print(s)

광주     40000.0
대전     35000.0
부산     52000.0
서울     70000.0
울릉도        NaN
Name: Series_from_dict, dtype: float64

In [ ]:
data = {'도시':['서울','서울','서울','부산','부산','부산'],
        '연도':[2020,2019,2018,2020,2019,2018],
        '인구수':[15865,15964,16034,4342,4380,4416]}
frame = pd.DataFrame(data)
frame

   도시    연도    인구수
0  서울  2020  15865
1  서울  2019  15964
2  서울  2018  16034
3  부산  2020   4342
4  부산  2019   4380
5  부산  2018   4416

In [ ]:
frame = pd.DataFrame(data,columns=['연도','도시','인구수'])
frame

     연도  도시    인구수
0  2020  서울  15865
1  2019  서울  15964
2  2018  서울  16034
3  2020  부산   4342
4  2019  부산   4380
5  2018  부산   4416

In [ ]:
frame = pd.DataFrame(data,columns=['연도','도시','인구수','변화율'])
frame

     연도  도시    인구수  변화율
0  2020  서울  15865  NaN
1  2019  서울  15964  NaN
2  2018  서울  16034  NaN
3  2020  부산   4342  NaN
4  2019  부산   4380  NaN
5  2018  부산   4416  NaN

In [ ]:
data = {'column1' : pd.Series(data=np.random.randint(10,100,5),index=['가','나','다','라','마']),
        'column2' : pd.Series(data=np.random.randint(10,100,5),index=['가','나','다','라','마']),
        'column3' : pd.Series(data=np.random.randint(10,100,5),index=['가','나','다','라','마'])
        }
frame = pd.DataFrame(data=data)
frame

   column1  column2  column3
가       47       12       44
나       67       82       85
다       81       25       49
라       41       17       42
마       14       83       17

In [ ]:
frame.values

array([[47, 12, 44],
       [67, 82, 85],
       [81, 25, 49],
       [41, 17, 42],
       [14, 83, 17]])

In [ ]:
df =pd.read_csv(r'/content/drive/MyDrive/빅데이터 분석/CSV/example_1.csv')
df

    a   b   c   d   e    keyword
0   1   2   3   4   5      Hello
1  11  12  13  14  15       Good
2  21  22  23  24  25       Nice
3  31  32  33  34  35  Beautiful
4  41  42  43  44  45       GoGo

In [ ]:
pd.read_table("/content/drive/MyDrive/빅데이터 분석/CSV/example_1.csv",sep=',')

    a   b   c   d   e    keyword
0   1   2   3   4   5      Hello
1  11  12  13  14  15       Good
2  21  22  23  24  25       Nice
3  31  32  33  34  35  Beautiful
4  41  42  43  44  45       GoGo

In [ ]:
df =pd.read_csv(r'/content/drive/MyDrive/빅데이터 분석/CSV/example_2.csv',header=None)
df

    0   1   2   3   4          5
0   1   2   3   4   5      Hello
1  11  12  13  14  15       Good
2  21  22  23  24  25       Nice
3  31  32  33  34  35  Beautiful
4  41  42  43  44  45       GoGo

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/빅데이터 분석/CSV/example_2.csv',
                 names=['columns1', 'columns2', 'columns3', 'columns4', 'columns5', 'columns6'])

df

   columns1  columns2  columns3  columns4  columns5   columns6
0         1         2         3         4         5      Hello
1        11        12        13        14        15       Good
2        21        22        23        24        25       Nice
3        31        32        33        34        35  Beautiful
4        41        42        43        44        45       GoGo

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/빅데이터 분석/CSV/example_2.csv',
                 names=['columns1', 'columns2', 'columns3', 'columns4', 'columns5', 'columns6'],
                 header=None)
df

   columns1  columns2  columns3  columns4  columns5   columns6
0         1         2         3         4         5      Hello
1        11        12        13        14        15       Good
2        21        22        23        24        25       Nice
3        31        32        33        34        35  Beautiful
4        41        42        43        44        45       GoGo

In [ ]:
col = ['컬럼1','컬럼2','컬럼3','컬럼4','컬럼5','키워드']
pd.read_csv(r'/content/drive/MyDrive/빅데이터 분석/CSV/example_2.csv',names=col)

   컬럼1  컬럼2  컬럼3  컬럼4  컬럼5        키워드
0    1    2    3    4    5      Hello
1   11   12   13   14   15       Good
2   21   22   23   24   25       Nice
3   31   32   33   34   35  Beautiful
4   41   42   43   44   45       GoGo

In [ ]:
col = ['컬럼1','컬럼2','컬럼3','컬럼4','컬럼5','키워드']
pd.read_csv(r'/content/drive/MyDrive/빅데이터 분석/CSV/example_2.csv',names=col,index_col='키워드')

           컬럼1  컬럼2  컬럼3  컬럼4  컬럼5
키워드
Hello        1    2    3    4    5
Good        11   12   13   14   15
Nice        21   22   23   24   25
Beautiful   31   32   33   34   35
GoGo        41   42   43   44   45

In [ ]:
pd.read_csv(r'/content/drive/MyDrive/빅데이터 분석/CSV/example_1.csv',skiprows=[1,3])

    a   b   c   d   e    keyword
0  11  12  13  14  15       Good
1  31  32  33  34  35  Beautiful
2  41  42  43  44  45       GoGo

In [ ]:
np_data = pd.read_csv('/content/drive/MyDrive/빅데이터 분석/CSV/example_3.csv')

In [ ]:
print(pd.isnull(np_data))

    step      a      b      c      d      e  keyword
0  False  False  False  False  False  False    False
1  False  False  False  False  False   True    False
2  False   True  False  False  False  False    False
3  False  False  False   True  False  False    False
4  False  False   True  False  False  False     True

In [ ]:
pd.isnull(np_data)

    step      a      b      c      d      e  keyword
0  False  False  False  False  False  False    False
1  False  False  False  False  False   True    False
2  False   True  False  False  False  False    False
3  False  False  False   True  False  False    False
4  False  False   True  False  False  False     True

In [ ]:
na_data=pd.read_csv('/content/drive/MyDrive/빅데이터 분석/CSV/example_3.csv',na_values=['Null','NaN','one','two'])
na_data

    step     a     b     c   d     e    keyword
0    NaN   1.0   2.0   3.0   4   5.0      Hello
1    NaN  11.0  12.0  13.0  14   NaN       Good
2  three   NaN  22.0  23.0  24  25.0       Nice
3   four  31.0  32.0   NaN  34  35.0  Beautiful
4   five  41.0   NaN  43.0  44  45.0        NaN

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/빅데이터 분석/CSV/score.csv")
df

       학번   이름  국어   수학  과학
0  251101  홍길동  90   90  60
1  251102  홍길순  85   90  80
2  251103  이철수  50   70  90
3  251104  김영희  80   60  70
4  251105  정선아  80   78  76
5  251106  이정민  80  100  90
6  251107  박동윤  70   75  80

In [ ]:
df.head()

       학번   이름  국어  수학  과학
0  251101  홍길동  90  90  60
1  251102  홍길순  85  90  80
2  251103  이철수  50  70  90
3  251104  김영희  80  60  70
4  251105  정선아  80  78  76

In [ ]:
df.tail(3)

       학번   이름  국어   수학  과학
4  251105  정선아  80   78  76
5  251106  이정민  80  100  90
6  251107  박동윤  70   75  80

In [ ]:
len(df)

7

In [ ]:
df.size

35

In [ ]:
df.shape

(7, 5)

In [ ]:
data = ['토끼','여우','곰','사자','하마']
s = pd.Series(data=data)
index2 = ['a','b','c','d','e']
d = pd.Series(data=data,index=index2)
s

0    토끼
1    여우
2     곰
3    사자
4    하마
dtype: object

In [ ]:
d

a    토끼
b    여우
c     곰
d    사자
e    하마
dtype: object

In [ ]:
id = pd.Series([251101, 251102, 251103, 251104])
name = pd.Series(['홀길동', '홍길순', '이철수', '김명희'])
kor = pd.Series([90, 85, 50, 80])
math = pd.Series([90, 90, 70, 60])
sci = pd.Series([60, 80, 90, 70])
eng = pd.Series([75, 80, 70, 60])

data = pd.DataFrame({
    'ID': id,
    '이름': name,
    '국어': kor,
    '수학': math,
    '과학': sci,
    '영어': eng
})

data

       ID   이름  국어  수학  과학  영어
0  251101  홀길동  90  90  60  75
1  251102  홍길순  85  90  80  80
2  251103  이철수  50  70  90  70
3  251104  김명희  80  60  70  60

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/빅데이터 분석/CSV/score.csv')
df

       학번   이름  국어   수학  과학
0  251101  홍길동  90   90  60
1  251102  홍길순  85   90  80
2  251103  이철수  50   70  90
3  251104  김영희  80   60  70
4  251105  정선아  80   78  76
5  251106  이정민  80  100  90
6  251107  박동윤  70   75  80

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/빅데이터 분석/CSV/score.csv',index_col=0)
df

         이름  국어   수학  과학
학번
251101  홍길동  90   90  60
251102  홍길순  85   90  80
251103  이철수  50   70  90
251104  김영희  80   60  70
251105  정선아  80   78  76
251106  이정민  80  100  90
251107  박동윤  70   75  80

In [ ]:
df.head()

         이름  국어  수학  과학
학번
251101  홍길동  90  90  60
251102  홍길순  85  90  80
251103  이철수  50  70  90
251104  김영희  80  60  70
251105  정선아  80  78  76

In [ ]:
df[:3]

         이름  국어  수학  과학
학번
251101  홍길동  90  90  60
251102  홍길순  85  90  80
251103  이철수  50  70  90

In [ ]:
df[-3:]

         이름  국어   수학  과학
학번
251105  정선아  80   78  76
251106  이정민  80  100  90
251107  박동윤  70   75  80

In [ ]:
df[['이름','국어']][:3]

         이름  국어
학번
251101  홍길동  90
251102  홍길순  85
251103  이철수  50