
menu_location = pd.DataFrame({
    '음식명': ['돈가스', '파스타', '파스타', '피자', '피자'],
    '매장위치': ['삼성동', '명동', '홍대입구', '이태원', '가로수길']})

menu_data1 = pd.DataFrame({
    '음식명': ['초밥', '초밥', '갈비탕', '짜장면', '짜장면'],
    '판매날짜': ['2021-10-01', '2021-10-02', '2021-10-01', '2021-10-01', '2021-10-02'],
    '메모': ['20000', '15000', '13000', '7000', '9000']})

menu_data2 = pd.DataFrame({'음식명': ['초밥', '갈비탕', '짜장면'],
                    '메모': ['일식', '한식', '중식']})

menu_price = pd.DataFrame({
    '음식명': ['초밥', '초밥', '갈비탕', '짜장면'],
    '가격': [20000, 15000, 13000, 7000]})

menu_score = pd.DataFrame({
    '메뉴명': ['초밥', '갈비탕', '갈비탕', '짜장면'],
    '단가': [10000, 7000, 6000, 3000]})

In [5]:
import pandas as pd
import numpy as np

rare_name=['Dr', 'Rev', 'y', 'Planke,', 'Impe,' , 'Gordon,', 'Col', 'Major','Melkebeke,','Jonkheer',
           'Shawah,', 'the', 'Velde,','Capt','Messemaeker,','Carlo,','Steen,','Mulder,','Pelsmaeker,',
           'Walle,','der','Billiard,','Don','Cruyssen,']

data_1 = pd.DataFrame({'음식명': ['돈가스', '피자', '초밥', '치킨', '탕수육'],
                    '카테고리': ['일식', '양식', '일식', '양식', '중식']})

data_2 = pd.DataFrame({'음식명': ['갈비탕', '냉면', '짜장면', '파스타', '라멘'],
                    '카테고리': ['한식', '한식', '중식', '양식', '일식']})

data_3 = pd.DataFrame({'음식명': ['갈비탕', '냉면', '짜장면', '파스타', '라멘'],
                    '판매인기지역': ['서울', '부산', '제주', '제주', '서울']})

data_4 = pd.DataFrame({'음식명': ['돈가스', '피자', '초밥', '치킨', '탕수육', '갈비탕', '냉면', '짜장면', '파스타', '라멘'],
                    '카테고리': ['일식', '양식', '일식', '양식', '중식', '한식', '한식', '중식', '양식', '일식']})

data_5 = pd.DataFrame({'음식명': ['탕수육', '짜장면', '돈가스', '치킨', '파스타', '갈비탕', '초밥'],
                    '판매인기지역': ['서울', '부산', '제주', '서울', '서울', '제주', '부산']})

data_6 = pd.DataFrame(data_4.merge(data_5))

data_7 = pd.DataFrame({'판매인기지역': ['서울', '부산', '제주'],
                    '오픈시간': ['10시', '12시', '11시']})

In [6]:
pd.merge(data_6,data_7)

   음식명 카테고리 판매인기지역 오픈시간
0  돈가스   일식     제주  11시
1   초밥   일식     부산  12시
2   치킨   양식     서울  10시
3  탕수육   중식     서울  10시
4  갈비탕   한식     제주  11시
5  짜장면   중식     부산  12시
6  파스타   양식     서울  10시

In [8]:
menu_price = pd.DataFrame({
    '음식명': ['돈가스','돈가스','파스타','파스타','파스타'],
    '가격': [9000, 10000, 12000, 13000, 150000]})

menu_price

   음식명      가격
0  돈가스    9000
1  돈가스   10000
2  파스타   12000
3  파스타   13000
4  파스타  150000

In [9]:
menu_location = pd.DataFrame({
    '음식명': ['돈가스', '파스타', '파스타', '피자', '피자'],
    '매장위치': ['삼성동', '명동', '홍대입구', '이태원', '가로수길']})
menu_location

   음식명  매장위치
0  돈가스   삼성동
1  파스타    명동
2  파스타  홍대입구
3   피자   이태원
4   피자  가로수길

In [10]:
pd.merge(menu_location,menu_price)

   음식명  매장위치      가격
0  돈가스   삼성동    9000
1  돈가스   삼성동   10000
2  파스타    명동   12000
3  파스타    명동   13000
4  파스타    명동  150000
5  파스타  홍대입구   12000
6  파스타  홍대입구   13000
7  파스타  홍대입구  150000

In [12]:
menu_data1 = pd.DataFrame({
    '음식명': ['초밥', '초밥', '갈비탕', '짜장면', '짜장면'],
    '판매날짜': ['2021-10-01', '2021-10-02', '2021-10-01', '2021-10-01', '2021-10-02'],
    '메모': ['20000', '15000', '13000', '7000', '9000']})
menu_data1

   음식명        판매날짜     메모
0   초밥  2021-10-01  20000
1   초밥  2021-10-02  15000
2  갈비탕  2021-10-01  13000
3  짜장면  2021-10-01   7000
4  짜장면  2021-10-02   9000

In [14]:
menu_data2 = pd.DataFrame({'음식명': ['초밥', '갈비탕', '짜장면'],
                    '메모': ['일식', '한식', '중식']})
menu_data2

   음식명  메모
0   초밥  일식
1  갈비탕  한식
2  짜장면  중식

In [16]:
pd.merge(menu_data2,menu_data1)

Empty DataFrame
Columns: [음식명, 메모, 판매날짜]
Index: []

In [17]:
pd.merge(menu_data2,menu_data1, on="음식명")

   음식명 메모_x        판매날짜   메모_y
0   초밥   일식  2021-10-01  20000
1   초밥   일식  2021-10-02  15000
2  갈비탕   한식  2021-10-01  13000
3  짜장면   중식  2021-10-01   7000
4  짜장면   중식  2021-10-02   9000

In [19]:
menu_price = pd.DataFrame({ '음식명': ['초밥', '초밥', '갈비탕', '짜장면'], '가격': [20000, 15000, 13000, 7000]})
menu_score = pd.DataFrame({ '메뉴명': ['초밥', '갈비탕', '갈비탕', '짜장면'], '단가': [10000, 7000, 6000, 3000]})

In [21]:
pd.merge(menu_price,menu_score,left_on="음식명",right_on="메뉴명")

   음식명     가격  메뉴명     단가
0   초밥  20000   초밥  10000
1   초밥  15000   초밥  10000
2  갈비탕  13000  갈비탕   7000
3  갈비탕  13000  갈비탕   6000
4  짜장면   7000  짜장면   3000

In [22]:
pd.merge(menu_price,menu_score,left_on="음식명",right_on="메뉴명").drop('메뉴명',axis=1)

   음식명     가격     단가
0   초밥  20000  10000
1   초밥  15000  10000
2  갈비탕  13000   7000
3  갈비탕  13000   6000
4  짜장면   7000   3000

In [23]:
menu_data1 = pd.DataFrame(
    [20000, 15000, 12000, 13000, 15000],
    index=['초밥', '초밥', '갈비탕', '갈비탕', '갈비탕'], columns=['가격'])

menu_data2 = pd.DataFrame(
    [12000, 7000, 8000, 9000, 25000],
    index=['갈비탕', '짜장면', '짜장면', '짜장면', '탕수육'], columns=['가격'])

In [25]:
#인덱스으로 기준으로 데이터 병합ㅎk기
pd.merge(menu_data1,menu_data2,how='outer')

      가격
0   7000
1   8000
2   9000
3  12000
4  13000
5  15000
6  15000
7  20000
8  25000

In [26]:
pd.merge(menu_data1,menu_data2,how='outer',left_index=True,right_index=True)

        가격_x     가격_y
갈비탕  12000.0  12000.0
갈비탕  13000.0  12000.0
갈비탕  15000.0  12000.0
짜장면      NaN   7000.0
짜장면      NaN   8000.0
짜장면      NaN   9000.0
초밥   20000.0      NaN
초밥   15000.0      NaN
탕수육      NaN  25000.0