# Numpy연습 : 기온 데이터 생성 및 분석

**step1 : 가상의 기온 데이터**

In [3]:
import pandas as pd
import numpy as np

# 재현성을 위해 랜덤 시드 설정
np.random.seed(42)

# 1년의 일별 기온 데이터 생성
days = np.arange(365) # 1년의 각 날짜를 나타내는 배열

# 계절별 기온 평균값 설정
seasonal_mean_temperatures = {
    "winter" : 5, # 겨울 평균 기온
    "spring" : 15, # 봄 평균 기온
    "summer" : 25, # 여름 평균 기온
    "fall" : 15, # 가을 평균 기온
}

# 계절 구간에 따라 평균값 적용
season = np.zeros(365)

season[:80] = seasonal_mean_temperatures["winter"] # 겨울 (1~80일)
season[80:172] = seasonal_mean_temperatures["spring"] # 봄 (80~172일)
season[172:264] = seasonal_mean_temperatures["summer"] # 여름 (172~264)
season[264:] = seasonal_mean_temperatures["fall"] # 가을 (264~365일)

# 계절별 기온 평균값에 난수를 추가해 변동성 부여
random_noise = np.random.normal(0,2,size = 365) # 하루 기온의 랜덤 변동성
daily_temperatures = season + random_noise # 계절 평균값에 난수 변동성 추가

# 첫 10일의 기온 출력
print("첫 10일의 기온 출력")
print(daily_temperatures[:10])

첫 10일의 기온 출력
[5.99342831 4.7234714  6.29537708 8.04605971 4.53169325 4.53172609
 8.15842563 6.53486946 4.06105123 6.08512009]

In [7]:
# 기본 통계 계산
mean_temp = np.mean(daily_temperatures) # 평균 기온
min_temp = np.min(daily_temperatures) # 최저 기온
max_temp = np.max(daily_temperatures) # 최고 기온
std_temp = np.std(daily_temperatures) # 표준 편차

print('\n 기본 데이터 통계 : ')
print(f"평균 기온 : {mean_temp : .2f}℃")
print(f"최저 기온 : {min_temp : .2f}℃")
print(f"최고 기온 : {max_temp : .2f}℃")
print(f"기온 표준 편차 : {std_temp : .2f}℃")

 기본 데이터 통계 :
평균 기온 :  15.35℃
최저 기온 : -0.24℃
최고 기온 :  32.71℃
기온 표준 편차 :  7.23℃

In [12]:
# 영하 (0℃ 미만)인 날짜 찾기

freezing_days = np.where(daily_temperatures<0)[0]
print(freezing_days)
print(f"영하인 날짜의 수 : {len(freezing_days)}Day")

[74]
영하인 날짜의 수 : 1Day

In [14]:
# 1년 중 가장 더운 날 찾기
hottset_day = np.argmax(daily_temperatures) # agrmax = 최대
print(f"\n 1년중 가장 더운 날 : {hottset_day+1}일째 , 기온 {daily_temperatures[hottset_day]: .2f}℃")

 1년중 가장 더운 날 : 210일째 , 기온  32.71℃

# Pandas 연습 : 매출 데이터 생성 및 분석



1.   데이터 생성 : 날짜별로 제품 (A,B,C)의 매출과 이익 데이터를 생성

2.   데이터 분석 : 전체 데이터의 요약 통계를 출력, 제품별 평균 매출을 계산 원별 총 매출을 계산

3.   데이터 시각화 : 제품별 평균 매출을 막대 그래프로 시각화 , 월별 총 매출을 선 그래프를 선 그래프로 시각화

In [23]:
import pandas as pd
import numpy as np

# 가상의 매출 데이터 생성
np.random.seed(42) # 재현을 뉘한 시드 설정

data = {
    "Date" : pd.date_range(start="2024-01-01", periods=100), # 100일 동안의 날짜
    "Product" : np.random.choice(["A","B","C"],100), # 제품 A,B,C 중 하나
    "Sales" : np.random.randint(50,500,100), # 매출 금액 (50~500)
    "Profit" : np.random.uniform(10,100,100)
}

# DataFrame 생성
df = pd.DataFrame(data)
df

         Date Product  Sales     Profit
0  2024-01-01       C    185  47.566990
1  2024-01-02       A    112  29.989703
2  2024-01-03       C    188  20.787883
3  2024-01-04       C    130  40.385365
4  2024-01-05       A    441  94.861873
..        ...     ...    ...        ...
95 2024-04-05       A    282  31.959068
96 2024-04-06       A    308  97.570950
97 2024-04-07       C    408  45.378795
98 2024-04-08       A    247  90.284190
99 2024-04-09       A    460  66.802476

[100 rows x 4 columns]

In [19]:
df.head()

        Data Product  Sales     Profit
0 2024-01-01       C    185  47.566990
1 2024-01-02       A    112  29.989703
2 2024-01-03       C    188  20.787883
3 2024-01-04       C    130  40.385365
4 2024-01-05       A    441  94.861873

In [20]:
df.info

<bound method DataFrame.info of          Data Product  Sales     Profit
0  2024-01-01       C    185  47.566990
1  2024-01-02       A    112  29.989703
2  2024-01-03       C    188  20.787883
3  2024-01-04       C    130  40.385365
4  2024-01-05       A    441  94.861873
..        ...     ...    ...        ...
95 2024-04-05       A    282  31.959068
96 2024-04-06       A    308  97.570950
97 2024-04-07       C    408  45.378795
98 2024-04-08       A    247  90.284190
99 2024-04-09       A    460  66.802476

[100 rows x 4 columns]>

In [21]:
df.describe()

                      Data       Sales      Profit
count                  100  100.000000  100.000000
mean   2024-02-19 12:00:00  267.810000   53.758557
min    2024-01-01 00:00:00   54.000000   10.455543
25%    2024-01-25 18:00:00  155.250000   31.715172
50%    2024-02-19 12:00:00  272.500000   55.664744
75%    2024-03-15 06:00:00  382.250000   72.520852
max    2024-04-09 00:00:00  498.000000   98.708541
std                    NaN  130.578951   25.932953

In [22]:
Product_sales_avg = df.groupby("Product")["Sales"].mean()
Product_sales_avg

Product
A    285.939394
B    255.888889
C    262.354839
Name: Sales, dtype: float64

In [ ]:
# 날짜에서 월 추출
df["Month"] = df["Data"]