In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [4]:
df = pd.read_csv('dataset/sonar3.csv',header=None)  # num 60 = 0(암석)/1(광석)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,0
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,0
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,0
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,0
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,0

In [21]:
X = df.iloc[:,0:60].values
y = df.iloc[:,60].values

In [22]:
model =Sequential()
model.add(Dense(24,input_shape=(60,),activation='relu',name='input'))
model.add(Dense(10,activation='relu',name='hidden'))
model.add(Dense(1,activation='sigmoid',name='output'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (Dense)               (None, 24)                1464

 hidden (Dense)              (None, 10)                250

 output (Dense)              (None, 1)                 11

=================================================================
Total params: 1,725
Trainable params: 1,725
Non-trainable params: 0
_________________________________________________________________

In [23]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [24]:
model.fit(x,y,epochs=200,batch_size=10)

Epoch 1/200
21/21 [==============================] - 0s 6ms/step - loss: 0.6915 - accuracy: 0.5385
Epoch 2/200
21/21 [==============================] - 0s 6ms/step - loss: 0.6812 - accuracy: 0.5769
Epoch 3/200
21/21 [==============================] - 0s 6ms/step - loss: 0.6731 - accuracy: 0.6154
Epoch 4/200
21/21 [==============================] - 0s 5ms/step - loss: 0.6667 - accuracy: 0.6442
Epoch 5/200
21/21 [==============================] - 0s 5ms/step - loss: 0.6615 - accuracy: 0.7115
Epoch 6/200
21/21 [==============================] - 0s 5ms/step - loss: 0.6510 - accuracy: 0.6971
Epoch 7/200
21/21 [==============================] - 0s 5ms/step - loss: 0.6324 - accuracy: 0.7019
Epoch 8/200
21/21 [==============================] - 0s 6ms/step - loss: 0.6154 - accuracy: 0.7308
Epoch 9/200
21/21 [==============================] - 0s 6ms/step - loss: 0.6021 - accuracy: 0.7596
Epoch 10/200
21/21 [==============================] - 0s 5ms/step - loss: 0.5879 - accuracy: 0.7644
Epoch 11/200
21/21 [==============================] - 0s 5ms/step - loss: 0.5721 - accuracy: 0.7644
Epoch 12/200
21/21 [==============================] - 0s 5ms/step - loss: 0.5560 - accuracy: 0.7885
Epoch 13/200
21/21 [==============================] - 0s 4ms/step - loss: 0.5461 - accuracy: 0.8029
Epoch 14/200
21/21 [==============================] - 0s 4ms/step - loss: 0.5307 - accuracy: 0.7981
Epoch 15/200
21/21 [==============================] - 0s 4ms/step - loss: 0.5250 - accuracy: 0.7981
Epoch 16/200
21/21 [==============================] - 0s 4ms/step - loss: 0.5052 - accuracy: 0.8269
Epoch 17/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4969 - accuracy: 0.8077
Epoch 18/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4812 - accuracy: 0.8317
Epoch 19/200
21/21 [==============================] - 0s 4ms/step - loss: 0.4708 - accuracy: 0.8173
Epoch 20/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4598 - accuracy: 0.8413
Epoch 21/200
21/21 [==============================] - 0s 2ms/step - loss: 0.4578 - accuracy: 0.8173
Epoch 22/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4359 - accuracy: 0.8221
Epoch 23/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4304 - accuracy: 0.8221
Epoch 24/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4309 - accuracy: 0.8173
Epoch 25/200
21/21 [==============================] - 0s 2ms/step - loss: 0.4178 - accuracy: 0.8221
Epoch 26/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4214 - accuracy: 0.8221
Epoch 27/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4052 - accuracy: 0.8269
Epoch 28/200
21/21 [==============================] - 0s 3ms/step - loss: 0.4015 - accuracy: 0.8269
Epoch 29/200
21/21 [==============================] - 0s 3ms/step - loss: 0.3884 - accuracy: 0.8462
Epoch 30/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3802 - accuracy: 0.8510
Epoch 31/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3761 - accuracy: 0.8413
Epoch 32/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3870 - accuracy: 0.8269
Epoch 33/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3867 - accuracy: 0.8317
Epoch 34/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3769 - accuracy: 0.8413
Epoch 35/200
21/21 [==============================] - 0s 3ms/step - loss: 0.3616 - accuracy: 0.8413
Epoch 36/200
21/21 [==============================] - 0s 3ms/step - loss: 0.3540 - accuracy: 0.8510
Epoch 37/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3540 - accuracy: 0.8798
Epoch 38/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3380 - accuracy: 0.8750
Epoch 39/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8750
Epoch 40/200
21/21 [==============================] - 0s 3ms/step - loss: 0.3297 - accuracy: 0.8750
Epoch 41/200
21/21 [==============================] - 0s 3ms/step - loss: 0.3213 - accuracy: 0.8846
Epoch 42/200
21/21 [==============================] - 0s 3ms/step - loss: 0.3191 - accuracy: 0.8894
Epoch 43/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3133 - accuracy: 0.8750
Epoch 44/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3045 - accuracy: 0.8798
Epoch 45/200
21/21 [==============================] - 0s 3ms/step - loss: 0.3158 - accuracy: 0.8750
Epoch 46/200
21/21 [==============================] - 0s 2ms/step - loss: 0.3100 - accuracy: 0.8750
Epoch 47/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2964 - accuracy: 0.8846
Epoch 48/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2941 - accuracy: 0.8894
Epoch 49/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2899 - accuracy: 0.8942
Epoch 50/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2816 - accuracy: 0.8990
Epoch 51/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2816 - accuracy: 0.8846
Epoch 52/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2887 - accuracy: 0.8894
Epoch 53/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2746 - accuracy: 0.8942
Epoch 54/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2698 - accuracy: 0.8990
Epoch 55/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2622 - accuracy: 0.8942
Epoch 56/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2581 - accuracy: 0.9038
Epoch 57/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2571 - accuracy: 0.8990
Epoch 58/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2506 - accuracy: 0.9135
Epoch 59/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2556 - accuracy: 0.9087
Epoch 60/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2424 - accuracy: 0.9135
Epoch 61/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2371 - accuracy: 0.9135
Epoch 62/200
21/21 [==============================] - 0s 3ms/step - loss: 0.2354 - accuracy: 0.9231
Epoch 63/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2368 - accuracy: 0.9135
Epoch 64/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2337 - accuracy: 0.9135
Epoch 65/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2299 - accuracy: 0.9231
Epoch 66/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2180 - accuracy: 0.9327
Epoch 67/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2287 - accuracy: 0.9135
Epoch 68/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2200 - accuracy: 0.9375
Epoch 69/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2148 - accuracy: 0.9375
Epoch 70/200
21/21 [==============================] - 0s 3ms/step - loss: 0.2075 - accuracy: 0.9375
Epoch 71/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2089 - accuracy: 0.9279
Epoch 72/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2072 - accuracy: 0.9519
Epoch 73/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2096 - accuracy: 0.9279
Epoch 74/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2148 - accuracy: 0.9327
Epoch 75/200
21/21 [==============================] - 0s 3ms/step - loss: 0.2077 - accuracy: 0.9231
Epoch 76/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1959 - accuracy: 0.9423
Epoch 77/200
21/21 [==============================] - 0s 2ms/step - loss: 0.2000 - accuracy: 0.9327
Epoch 78/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1888 - accuracy: 0.9519
Epoch 79/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1914 - accuracy: 0.9375
Epoch 80/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1828 - accuracy: 0.9519
Epoch 81/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1845 - accuracy: 0.9327
Epoch 82/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1790 - accuracy: 0.9567
Epoch 83/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1744 - accuracy: 0.9567
Epoch 84/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1788 - accuracy: 0.9519
Epoch 85/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1775 - accuracy: 0.9567
Epoch 86/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1787 - accuracy: 0.9567
Epoch 87/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1890 - accuracy: 0.9327
Epoch 88/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1749 - accuracy: 0.9567
Epoch 89/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1623 - accuracy: 0.9663
Epoch 90/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1643 - accuracy: 0.9375
Epoch 91/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1733 - accuracy: 0.9423
Epoch 92/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1617 - accuracy: 0.9471
Epoch 93/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1574 - accuracy: 0.9519
Epoch 94/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1496 - accuracy: 0.9567
Epoch 95/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1468 - accuracy: 0.9519
Epoch 96/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1515 - accuracy: 0.9567
Epoch 97/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1507 - accuracy: 0.9519
Epoch 98/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1415 - accuracy: 0.9615
Epoch 99/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1464 - accuracy: 0.9712
Epoch 100/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1478 - accuracy: 0.9663
Epoch 101/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1420 - accuracy: 0.9663
Epoch 102/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1379 - accuracy: 0.9712
Epoch 103/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1381 - accuracy: 0.9663
Epoch 104/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1277 - accuracy: 0.9760
Epoch 105/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1302 - accuracy: 0.9663
Epoch 106/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1264 - accuracy: 0.9760
Epoch 107/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1300 - accuracy: 0.9712
Epoch 108/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1365 - accuracy: 0.9615
Epoch 109/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1220 - accuracy: 0.9808
Epoch 110/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1257 - accuracy: 0.9760
Epoch 111/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1185 - accuracy: 0.9808
Epoch 112/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1195 - accuracy: 0.9712
Epoch 113/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1128 - accuracy: 0.9808
Epoch 114/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1318 - accuracy: 0.9615
Epoch 115/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1155 - accuracy: 0.9808
Epoch 116/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1110 - accuracy: 0.9808
Epoch 117/200
21/21 [==============================] - 0s 4ms/step - loss: 0.1188 - accuracy: 0.9663
Epoch 118/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1283 - accuracy: 0.9615
Epoch 119/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1094 - accuracy: 0.9808
Epoch 120/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1038 - accuracy: 0.9760
Epoch 121/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1074 - accuracy: 0.9856
Epoch 122/200
21/21 [==============================] - 0s 2ms/step - loss: 0.1022 - accuracy: 0.9808
Epoch 123/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0998 - accuracy: 0.9808
Epoch 124/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0975 - accuracy: 0.9856
Epoch 125/200
21/21 [==============================] - 0s 3ms/step - loss: 0.1052 - accuracy: 0.9808
Epoch 126/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0926 - accuracy: 0.9904
Epoch 127/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0921 - accuracy: 0.9904
Epoch 128/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0972 - accuracy: 0.9760
Epoch 129/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0927 - accuracy: 0.9856
Epoch 130/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0919 - accuracy: 0.9808
Epoch 131/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0918 - accuracy: 0.9856
Epoch 132/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0869 - accuracy: 0.9808
Epoch 133/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0873 - accuracy: 0.9904
Epoch 134/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0844 - accuracy: 0.9904
Epoch 135/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0876 - accuracy: 0.9856
Epoch 136/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0838 - accuracy: 0.9856
Epoch 137/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0912 - accuracy: 0.9712
Epoch 138/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0890 - accuracy: 0.9856
Epoch 139/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0839 - accuracy: 0.9808
Epoch 140/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0788 - accuracy: 0.9952
Epoch 141/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0793 - accuracy: 0.9856
Epoch 142/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0775 - accuracy: 0.9856
Epoch 143/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0738 - accuracy: 0.9904
Epoch 144/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0726 - accuracy: 0.9904
Epoch 145/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0732 - accuracy: 0.9904
Epoch 146/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0757 - accuracy: 0.9904
Epoch 147/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0710 - accuracy: 0.9904
Epoch 148/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0712 - accuracy: 0.9904
Epoch 149/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0721 - accuracy: 0.9904
Epoch 150/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0679 - accuracy: 0.9856
Epoch 151/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0672 - accuracy: 0.9952
Epoch 152/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0738 - accuracy: 0.9856
Epoch 153/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0651 - accuracy: 0.9904
Epoch 154/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0641 - accuracy: 0.9952
Epoch 155/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0642 - accuracy: 0.9904
Epoch 156/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0651 - accuracy: 0.9952
Epoch 157/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0605 - accuracy: 0.9904
Epoch 158/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0611 - accuracy: 0.9904
Epoch 159/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0624 - accuracy: 0.9952
Epoch 160/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0599 - accuracy: 0.9952
Epoch 161/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0593 - accuracy: 0.9952
Epoch 162/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0589 - accuracy: 0.9904
Epoch 163/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0569 - accuracy: 0.9904
Epoch 164/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0599 - accuracy: 0.9952
Epoch 165/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0601 - accuracy: 0.9952
Epoch 166/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0560 - accuracy: 0.9952
Epoch 167/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0542 - accuracy: 0.9952
Epoch 168/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0576 - accuracy: 0.9952
Epoch 169/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0533 - accuracy: 0.9952
Epoch 170/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0533 - accuracy: 0.9952
Epoch 171/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0556 - accuracy: 0.9904
Epoch 172/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0503 - accuracy: 0.9952
Epoch 173/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0542 - accuracy: 0.9952
Epoch 174/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0521 - accuracy: 0.9952
Epoch 175/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0505 - accuracy: 0.9952
Epoch 176/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0500 - accuracy: 0.9952
Epoch 177/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0479 - accuracy: 0.9952
Epoch 178/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0489 - accuracy: 0.9952
Epoch 179/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0458 - accuracy: 0.9952
Epoch 180/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0460 - accuracy: 0.9952
Epoch 181/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0483 - accuracy: 0.9952
Epoch 182/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0454 - accuracy: 0.9952
Epoch 183/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0449 - accuracy: 0.9952
Epoch 184/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0439 - accuracy: 0.9952
Epoch 185/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0440 - accuracy: 0.9952
Epoch 186/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0449 - accuracy: 0.9952
Epoch 187/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0458 - accuracy: 0.9952
Epoch 188/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0458 - accuracy: 0.9952
Epoch 189/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0421 - accuracy: 0.9952
Epoch 190/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0401 - accuracy: 0.9952
Epoch 191/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0400 - accuracy: 0.9952
Epoch 192/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0413 - accuracy: 0.9952
Epoch 193/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0391 - accuracy: 0.9952
Epoch 194/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0384 - accuracy: 0.9952
Epoch 195/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0376 - accuracy: 0.9952
Epoch 196/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0378 - accuracy: 0.9952
Epoch 197/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0412 - accuracy: 0.9952
Epoch 198/200
21/21 [==============================] - 0s 2ms/step - loss: 0.0374 - accuracy: 0.9952
Epoch 199/200
21/21 [==============================] - 0s 3ms/step - loss: 0.0372 - accuracy: 0.9952

In [25]:
loss, acc = model.evaluate(x,y)
print("정확도 :",acc*100)

7/7 [==============================] - 0s 2ms/step - loss: 0.0396 - accuracy: 0.9952
정확도 : 99.5192289352417

In [26]:
# !pip install scikit-learn==1.6.1

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
df = pd.read_csv('dataset/sonar3.csv',header=None)  # num[column=60] = 0(암석)/1(광석)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,0
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,0
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,0
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,0
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,0

In [29]:
x = df.iloc[:,0:60].values
y = df.iloc[:,60].values

In [30]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3,shuffle=True)

In [31]:
model =Sequential()
model.add(Dense(24,input_shape=(60,),activation='relu',name='input'))
model.add(Dense(10,activation='relu',name='hidden'))
model.add(Dense(1,activation='sigmoid',name='output'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (Dense)               (None, 24)                1464

 hidden (Dense)              (None, 10)                250

 output (Dense)              (None, 1)                 11

=================================================================
Total params: 1,725
Trainable params: 1,725
Non-trainable params: 0
_________________________________________________________________

In [32]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [33]:
model.fit(X_train,y_train,epochs=200,batch_size=10)

Epoch 1/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6935 - accuracy: 0.5379
Epoch 2/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6849 - accuracy: 0.5448
Epoch 3/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6798 - accuracy: 0.5793
Epoch 4/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6742 - accuracy: 0.6276
Epoch 5/200
15/15 [==============================] - 0s 4ms/step - loss: 0.6682 - accuracy: 0.6483
Epoch 6/200
15/15 [==============================] - 0s 2ms/step - loss: 0.6639 - accuracy: 0.6690
Epoch 7/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6538 - accuracy: 0.6621
Epoch 8/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6449 - accuracy: 0.6690
Epoch 9/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6350 - accuracy: 0.6759
Epoch 10/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6277 - accuracy: 0.7241
Epoch 11/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6139 - accuracy: 0.6759
Epoch 12/200
15/15 [==============================] - 0s 3ms/step - loss: 0.6027 - accuracy: 0.7172
Epoch 13/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5920 - accuracy: 0.7448
Epoch 14/200
15/15 [==============================] - 0s 2ms/step - loss: 0.5785 - accuracy: 0.7172
Epoch 15/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5709 - accuracy: 0.7862
Epoch 16/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5564 - accuracy: 0.7586
Epoch 17/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5470 - accuracy: 0.7655
Epoch 18/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5343 - accuracy: 0.8069
Epoch 19/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5279 - accuracy: 0.7517
Epoch 20/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5161 - accuracy: 0.8207
Epoch 21/200
15/15 [==============================] - 0s 3ms/step - loss: 0.5082 - accuracy: 0.7793
Epoch 22/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4916 - accuracy: 0.8138
Epoch 23/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4844 - accuracy: 0.8345
Epoch 24/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4759 - accuracy: 0.8276
Epoch 25/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4672 - accuracy: 0.8069
Epoch 26/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4593 - accuracy: 0.8483
Epoch 27/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4509 - accuracy: 0.8621
Epoch 28/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4594 - accuracy: 0.7931
Epoch 29/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4365 - accuracy: 0.8621
Epoch 30/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4327 - accuracy: 0.8552
Epoch 31/200
15/15 [==============================] - 0s 2ms/step - loss: 0.4239 - accuracy: 0.8207
Epoch 32/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4202 - accuracy: 0.8552
Epoch 33/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4123 - accuracy: 0.8552
Epoch 34/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4083 - accuracy: 0.8621
Epoch 35/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4016 - accuracy: 0.8621
Epoch 36/200
15/15 [==============================] - 0s 3ms/step - loss: 0.4004 - accuracy: 0.8621
Epoch 37/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3883 - accuracy: 0.8759
Epoch 38/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3859 - accuracy: 0.8621
Epoch 39/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3793 - accuracy: 0.8483
Epoch 40/200
15/15 [==============================] - 0s 4ms/step - loss: 0.3737 - accuracy: 0.8828
Epoch 41/200
15/15 [==============================] - 0s 2ms/step - loss: 0.3691 - accuracy: 0.8759
Epoch 42/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3649 - accuracy: 0.8828
Epoch 43/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3729 - accuracy: 0.8621
Epoch 44/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3614 - accuracy: 0.8759
Epoch 45/200
15/15 [==============================] - 0s 2ms/step - loss: 0.3527 - accuracy: 0.8759
Epoch 46/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3563 - accuracy: 0.8690
Epoch 47/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3452 - accuracy: 0.8828
Epoch 48/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3385 - accuracy: 0.8828
Epoch 49/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3354 - accuracy: 0.8897
Epoch 50/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3360 - accuracy: 0.8966
Epoch 51/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3271 - accuracy: 0.8897
Epoch 52/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3292 - accuracy: 0.8690
Epoch 53/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3209 - accuracy: 0.8897
Epoch 54/200
15/15 [==============================] - 0s 2ms/step - loss: 0.3231 - accuracy: 0.9034
Epoch 55/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3238 - accuracy: 0.8759
Epoch 56/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3143 - accuracy: 0.8897
Epoch 57/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3088 - accuracy: 0.8828
Epoch 58/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3042 - accuracy: 0.8966
Epoch 59/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3036 - accuracy: 0.8828
Epoch 60/200
15/15 [==============================] - 0s 3ms/step - loss: 0.3061 - accuracy: 0.8690
Epoch 61/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2935 - accuracy: 0.9103
Epoch 62/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2892 - accuracy: 0.8966
Epoch 63/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2896 - accuracy: 0.9103
Epoch 64/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2824 - accuracy: 0.8966
Epoch 65/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2755 - accuracy: 0.9034
Epoch 66/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2733 - accuracy: 0.8966
Epoch 67/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2714 - accuracy: 0.9103
Epoch 68/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2732 - accuracy: 0.9034
Epoch 69/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2628 - accuracy: 0.9103
Epoch 70/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2630 - accuracy: 0.8966
Epoch 71/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2549 - accuracy: 0.9034
Epoch 72/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2514 - accuracy: 0.9172
Epoch 73/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2475 - accuracy: 0.9172
Epoch 74/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2471 - accuracy: 0.9103
Epoch 75/200
15/15 [==============================] - 0s 4ms/step - loss: 0.2424 - accuracy: 0.9172
Epoch 76/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2373 - accuracy: 0.9310
Epoch 77/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2356 - accuracy: 0.9241
Epoch 78/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2406 - accuracy: 0.8828
Epoch 79/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2348 - accuracy: 0.9310
Epoch 80/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2273 - accuracy: 0.9310
Epoch 81/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2243 - accuracy: 0.9172
Epoch 82/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2257 - accuracy: 0.9379
Epoch 83/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2201 - accuracy: 0.9034
Epoch 84/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2199 - accuracy: 0.9310
Epoch 85/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2162 - accuracy: 0.9172
Epoch 86/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2108 - accuracy: 0.9172
Epoch 87/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2125 - accuracy: 0.9172
Epoch 88/200
15/15 [==============================] - 0s 3ms/step - loss: 0.2029 - accuracy: 0.9379
Epoch 89/200
15/15 [==============================] - 0s 4ms/step - loss: 0.2127 - accuracy: 0.9103
Epoch 90/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1986 - accuracy: 0.9448
Epoch 91/200
15/15 [==============================] - 0s 2ms/step - loss: 0.1975 - accuracy: 0.9379
Epoch 92/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1921 - accuracy: 0.9310
Epoch 93/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1914 - accuracy: 0.9310
Epoch 94/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1932 - accuracy: 0.9310
Epoch 95/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1942 - accuracy: 0.9310
Epoch 96/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1819 - accuracy: 0.9310
Epoch 97/200
15/15 [==============================] - 0s 2ms/step - loss: 0.1871 - accuracy: 0.9448
Epoch 98/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1797 - accuracy: 0.9448
Epoch 99/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1752 - accuracy: 0.9517
Epoch 100/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1709 - accuracy: 0.9310
Epoch 101/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1676 - accuracy: 0.9241
Epoch 102/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1683 - accuracy: 0.9517
Epoch 103/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1678 - accuracy: 0.9517
Epoch 104/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1596 - accuracy: 0.9379
Epoch 105/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1756 - accuracy: 0.9241
Epoch 106/200
15/15 [==============================] - 0s 2ms/step - loss: 0.1570 - accuracy: 0.9655
Epoch 107/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1546 - accuracy: 0.9655
Epoch 108/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1543 - accuracy: 0.9586
Epoch 109/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1463 - accuracy: 0.9655
Epoch 110/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1549 - accuracy: 0.9448
Epoch 111/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1459 - accuracy: 0.9655
Epoch 112/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1512 - accuracy: 0.9517
Epoch 113/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1412 - accuracy: 0.9655
Epoch 114/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1478 - accuracy: 0.9586
Epoch 115/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1444 - accuracy: 0.9586
Epoch 116/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1323 - accuracy: 0.9793
Epoch 117/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1335 - accuracy: 0.9724
Epoch 118/200
15/15 [==============================] - 0s 2ms/step - loss: 0.1278 - accuracy: 0.9724
Epoch 119/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1363 - accuracy: 0.9655
Epoch 120/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1395 - accuracy: 0.9724
Epoch 121/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1372 - accuracy: 0.9655
Epoch 122/200
15/15 [==============================] - 0s 2ms/step - loss: 0.1329 - accuracy: 0.9724
Epoch 123/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1251 - accuracy: 0.9724
Epoch 124/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1190 - accuracy: 0.9793
Epoch 125/200
15/15 [==============================] - 0s 2ms/step - loss: 0.1159 - accuracy: 0.9793
Epoch 126/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1136 - accuracy: 0.9724
Epoch 127/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1219 - accuracy: 0.9793
Epoch 128/200
15/15 [==============================] - 0s 2ms/step - loss: 0.1102 - accuracy: 0.9793
Epoch 129/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1091 - accuracy: 0.9862
Epoch 130/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1048 - accuracy: 0.9931
Epoch 131/200
15/15 [==============================] - 0s 4ms/step - loss: 0.1055 - accuracy: 0.9862
Epoch 132/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1047 - accuracy: 0.9931
Epoch 133/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1036 - accuracy: 0.9862
Epoch 134/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1002 - accuracy: 0.9931
Epoch 135/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0992 - accuracy: 0.9931
Epoch 136/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1000 - accuracy: 0.9793
Epoch 137/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0951 - accuracy: 0.9931
Epoch 138/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0997 - accuracy: 0.9793
Epoch 139/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1033 - accuracy: 0.9793
Epoch 140/200
15/15 [==============================] - 0s 3ms/step - loss: 0.1035 - accuracy: 0.9724
Epoch 141/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0929 - accuracy: 0.9862
Epoch 142/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0891 - accuracy: 0.9931
Epoch 143/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0932 - accuracy: 0.9862
Epoch 144/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0878 - accuracy: 0.9931
Epoch 145/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0877 - accuracy: 0.9931
Epoch 146/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0825 - accuracy: 0.9931
Epoch 147/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0815 - accuracy: 0.9931
Epoch 148/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0824 - accuracy: 0.9931
Epoch 149/200
15/15 [==============================] - 0s 4ms/step - loss: 0.0796 - accuracy: 0.9931
Epoch 150/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0790 - accuracy: 0.9931
Epoch 151/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0787 - accuracy: 0.9931
Epoch 152/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0768 - accuracy: 1.0000
Epoch 153/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0752 - accuracy: 0.9931
Epoch 154/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0728 - accuracy: 0.9931
Epoch 155/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0719 - accuracy: 0.9931
Epoch 156/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0710 - accuracy: 0.9931
Epoch 157/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0726 - accuracy: 0.9931
Epoch 158/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0695 - accuracy: 1.0000
Epoch 159/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0710 - accuracy: 0.9931
Epoch 160/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0669 - accuracy: 0.9931
Epoch 161/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0661 - accuracy: 0.9931
Epoch 162/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0692 - accuracy: 0.9931
Epoch 163/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0642 - accuracy: 0.9931
Epoch 164/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0677 - accuracy: 0.9931
Epoch 165/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0640 - accuracy: 0.9931
Epoch 166/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0708 - accuracy: 1.0000
Epoch 167/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0677 - accuracy: 0.9862
Epoch 168/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0620 - accuracy: 1.0000
Epoch 169/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0593 - accuracy: 0.9931
Epoch 170/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0568 - accuracy: 1.0000
Epoch 171/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0599 - accuracy: 0.9931
Epoch 172/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0594 - accuracy: 0.9931
Epoch 173/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0637 - accuracy: 0.9931
Epoch 174/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0617 - accuracy: 0.9862
Epoch 175/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0572 - accuracy: 0.9931
Epoch 176/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0546 - accuracy: 1.0000
Epoch 177/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0500 - accuracy: 0.9931
Epoch 178/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0503 - accuracy: 0.9931
Epoch 179/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0484 - accuracy: 1.0000
Epoch 180/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0494 - accuracy: 0.9931
Epoch 181/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0487 - accuracy: 0.9931
Epoch 182/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0469 - accuracy: 1.0000
Epoch 183/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0496 - accuracy: 0.9931
Epoch 184/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0461 - accuracy: 1.0000
Epoch 185/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0440 - accuracy: 1.0000
Epoch 186/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0454 - accuracy: 1.0000
Epoch 187/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0429 - accuracy: 1.0000
Epoch 188/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0434 - accuracy: 0.9931
Epoch 189/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0431 - accuracy: 0.9931
Epoch 190/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0448 - accuracy: 1.0000
Epoch 191/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0451 - accuracy: 0.9931
Epoch 192/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0397 - accuracy: 1.0000
Epoch 193/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0395 - accuracy: 1.0000
Epoch 194/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0392 - accuracy: 1.0000
Epoch 195/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0393 - accuracy: 1.0000
Epoch 196/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0372 - accuracy: 1.0000
Epoch 197/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0357 - accuracy: 1.0000
Epoch 198/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0351 - accuracy: 1.0000
Epoch 199/200
15/15 [==============================] - 0s 3ms/step - loss: 0.0367 - accuracy: 1.0000

In [34]:
loss, acc = model.evaluate(X_test,y_test)
print("정확도 :",acc*100)

2/2 [==============================] - 0s 4ms/step - loss: 0.7204 - accuracy: 0.8413
정확도 : 84.1269850730896

In [40]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import KFold

df = pd.read_csv('dataset/sonar3.csv', header=None)

X = df.iloc[:, 0:60]
y = df.iloc[:, 60]

k = 5
kfold = KFold(n_splits=k, shuffle=True, random_state=42)
acc_score = []

def model_fn():
    model = Sequential()
    model.add(Dense(24, input_shape=(60,), activation='relu', name='input'))
    model.add(Dense(10, activation='relu', name='hidden'))
    model.add(Dense(1, activation='sigmoid', name='output'))
    return model
    
for train_idx, test_idx in kfold.split(X):
    X_train, X_test = X.iloc[train_idx, :], X.iloc[test_idx, :]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model = model_fn()
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=200, batch_size=10, verbose=0)

    loss, acc = model.evaluate(X_test, y_test, verbose=0)
    acc_score.append(acc)


acc_avg = sum(acc_score) / k
print('정확도:', acc_score)
print('정확도 평균:', acc_avg)

WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_test_function.<locals>.test_function at 0x000002615FA58160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 16 calls to <function Model.make_test_function.<locals>.test_function at 0x000002615FA5A050> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
정확도: [0.9285714030265808, 0.761904776096344, 0.8571428656578064, 0.8292682766914368, 0.9268292784690857]
정확도 평균: 0.8607433199882507