In [ ]:
import numpy
import pandas as pd

data = {
    'name': ['Spaghetti Carbonara', 'Caesar Salad', 'Margarita Pizza', 'Tiramisu', 'Chicken Alfredo',
             'Margherita Pizza', 'Lasagna', 'Greek Salad', 'Panna Cotta', 'Risotto'],
    'price': [12.5, 8.0, 10.0, 6.5, 13.0, 9.5, 11.5, 7.5, 5.5, 14.0],
    'calories': [700, 400, 800, 400, 900, 850, 950, 400, 350, 650],
    'category': ['Pasta', 'Salad', 'Pizza', 'Dessert', 'Pasta', 'Pizza', 'Pasta', 'Salad', 'Dessert', 'Rice']
}

df = pd.DataFrame(data)

df.to_csv('pandas_data3_csv',index = False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.to_csv('/content/drive/My Drive/pandas_data3.csv',index=False)

In [ ]:
df = pd.read_csv('/content/drive/My Drive/pandas_data.csv')
df

                  name  price  calories category
0  Spaghetti Carbonara   12.5       700    Pasta
1         Caesar Salad    8.0       400    Salad
2      Margarita Pizza   10.0       800    Pizza
3             Tiramisu    6.5       400  Dessert
4      Chicken Alfredo   13.0       900    Pasta
5     Margherita Pizza    9.5       850    Pizza
6              Lasagna   11.5       950    Pasta
7          Greek Salad    7.5       400    Salad
8          Panna Cotta    5.5       350  Dessert
9              Risotto   14.0       650     Rice

In [ ]:
df.head()

                  name  price  calories category
0  Spaghetti Carbonara   12.5       700    Pasta
1         Caesar Salad    8.0       400    Salad
2      Margarita Pizza   10.0       800    Pizza
3             Tiramisu    6.5       400  Dessert
4      Chicken Alfredo   13.0       900    Pasta

In [ ]:
df.tail(7)

               name  price  calories category
3          Tiramisu    6.5       400  Dessert
4   Chicken Alfredo   13.0       900    Pasta
5  Margherita Pizza    9.5       850    Pizza
6           Lasagna   11.5       950    Pasta
7       Greek Salad    7.5       400    Salad
8       Panna Cotta    5.5       350  Dessert
9           Risotto   14.0       650     Rice

In [ ]:
df.sample(3)

                  name  price  calories category
0  Spaghetti Carbonara   12.5       700    Pasta
3             Tiramisu    6.5       400  Dessert
7          Greek Salad    7.5       400    Salad

In [ ]:
df.shape

(10, 4)

In [ ]:
df.columns

Index(['name', 'price', 'calories', 'category'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   price     10 non-null     float64
 2   calories  10 non-null     int64
 3   category  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes

In [ ]:
df.describe()

           price    calories
count  10.000000   10.000000
mean    9.800000  640.000000
std     2.907844  234.283779
min     5.500000  350.000000
25%     7.625000  400.000000
50%     9.750000  675.000000
75%    12.250000  837.500000
max    14.000000  950.000000

In [ ]:
df['calories'].value_counts()

calories
400    3
700    1
800    1
900    1
850    1
950    1
350    1
650    1
Name: count, dtype: int64

In [ ]:
df['price'].value_counts()

price
12.5    1
8.0     1
10.0    1
6.5     1
13.0    1
9.5     1
11.5    1
7.5     1
5.5     1
14.0    1
Name: count, dtype: int64

In [ ]:
df.isnull()

    name  price  calories  category
0  False  False     False     False
1  False  False     False     False
2  False  False     False     False
3  False  False     False     False
4  False  False     False     False
5  False  False     False     False
6  False  False     False     False
7  False  False     False     False
8  False  False     False     False
9  False  False     False     False

In [ ]:
df.isnull().sum()

name        0
price       0
calories    0
category    0
dtype: int64

In [ ]:
df['category']

0      Pasta
1      Salad
2      Pizza
3    Dessert
4      Pasta
5      Pizza
6      Pasta
7      Salad
8    Dessert
9       Rice
Name: category, dtype: object

In [ ]:
df.loc[0,'name']

'Spaghetti Carbonara'

In [ ]:
df[df['calories']==700]

                  name  price  calories category
0  Spaghetti Carbonara   12.5       700    Pasta

In [ ]:
df[df['calories']<=700]

                  name  price  calories category
0  Spaghetti Carbonara   12.5       700    Pasta
1         Caesar Salad    8.0       400    Salad
3             Tiramisu    6.5       400  Dessert
7          Greek Salad    7.5       400    Salad
8          Panna Cotta    5.5       350  Dessert
9              Risotto   14.0       650     Rice

In [ ]:
df.loc[df['price']==5.5,'price'] = 6.5
df

                  name price  calories category
0  Spaghetti Carbonara  12.5       700    Pasta
1         Caesar Salad   8.0       400    Salad
2      Margarita Pizza  10.0       800    Pizza
3             Tiramisu   6.5       400  Dessert
4      Chicken Alfredo  13.0       900    Pasta
5     Margherita Pizza   9.5       850    Pizza
6              Lasagna  11.5       950    Pasta
7          Greek Salad   7.5       400    Salad
8          Panna Cotta   6.5       350  Dessert
9              Risotto  14.0       650     Rice

In [ ]:
sorted_df = df.sort_values(by='category')
sorted_df

                  name price  calories category
3             Tiramisu   6.5       400  Dessert
8          Panna Cotta   6.5       350  Dessert
0  Spaghetti Carbonara  12.5       700    Pasta
4      Chicken Alfredo  13.0       900    Pasta
6              Lasagna  11.5       950    Pasta
2      Margarita Pizza  10.0       800    Pizza
5     Margherita Pizza   9.5       850    Pizza
9              Risotto  14.0       650     Rice
1         Caesar Salad   8.0       400    Salad
7          Greek Salad   7.5       400    Salad

In [ ]:
df['price'] = df['price']+1
df

                  name price  calories category
0  Spaghetti Carbonara  13.5       700    Pasta
1         Caesar Salad   9.0       400    Salad
2      Margarita Pizza  11.0       800    Pizza
3             Tiramisu   7.5       400  Dessert
4      Chicken Alfredo  14.0       900    Pasta
5     Margherita Pizza  10.5       850    Pizza
6              Lasagna  12.5       950    Pasta
7          Greek Salad   8.5       400    Salad
8          Panna Cotta   7.5       350  Dessert
9              Risotto  15.0       650     Rice