# **CSV 파일 구글 드라이브에 만들기**
- pandas로 데이터 생성후 csv 파일로 저장하기

In [11]:
import numpy as np
import pandas as pd

#데이터 플레임 생성
data = {
    'name': ['Alice','Bob','Charlie','Diana','Eve','Jack','Tom','Emma'],
    'age' : [14,13,15,14,13,16,15,15],
    'grade':['A','B','A','C','B','C','A','A']
        }

df = pd.DataFrame(data)

#CSV파일로 저장
df.to_csv('sample_data_csv',index=False)

위 코드에서 index=False는 데이터프레임을 csv파일로 저장할 때 인덱스 열을 포함하지 않도록 저장하는 옵션이다

위  코드는 sample_data.csv을 colab의 기본 작업 디렉토리에 저장

# **Google** **Drive에** **CSV파일** **저장하기**

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**/Content**

=> Google Colab의 기본 작업 디렉토리. 모든 colab 세션은 /content 폴더를 루트로 시작

In [14]:
#Google Drive에 csv파일로 저장
df.to_csv('/content/drive/My Drive/sample_data.csv',index=False)

/content/drive
* My Drive는 Google Drive의 기본 저장소
* 사용자의 Google Drive 최상위 폴더
* Google Drive의 내 드라이브에 저장한 파일과 폴더가 이 경로 아래에 위치합니다.
* /content/drive/My Drive 경로를 통해 Google Drive의 파일과 폴더에 접근. /content/drive/My drive/smaple_data.csv

마지막으로, Smaple_data.csv는 Google Drive의 My Drive 최상위 폴더에 저장되는 파일 이름임

이 경로는 Google Drive의 내 드라이브 폴더에 smaple_data.csv 파일을 저장하겠다는 의미

# **기본 파일 불러오기 및 데이터 확인**

In [21]:
import pandas as pd

#csv파일 불러오기
df = pd.read_csv('/content/drive/My Drive/sample_data.csv')

#데이터 확인
print('Data Overview:')
df

Data Overview:

      name  age grade
0    Alice   14     A
1      Bob   13     B
2  Charlie   15     A
3    Diana   14     C
4      Eve   13     B
5     Jack   16     C
6      Tom   15     A
7     Emma   15     A

처음 몇 개의 행 확인

In [24]:
#처음 5개 행 출력
df.head() # head = 기본 5개

      name  age grade
0    Alice   14     A
1      Bob   13     B
2  Charlie   15     A
3    Diana   14     C
4      Eve   13     B

In [25]:
#운하는 수만큼 출력하기 .head(수)
df.head(7)

      name  age grade
0    Alice   14     A
1      Bob   13     B
2  Charlie   15     A
3    Diana   14     C
4      Eve   13     B
5     Jack   16     C
6      Tom   15     A

마지맞 몇 개의 행을 확인하기

In [26]:
#마지막 5개의 행 확인하기
df.tail()

    name  age grade
3  Diana   14     C
4    Eve   13     B
5   Jack   16     C
6    Tom   15     A
7   Emma   15     A

In [27]:
#원하는 수 만큼 출력하기 .tail(수)
df.tail(7)

      name  age grade
1      Bob   13     B
2  Charlie   15     A
3    Diana   14     C
4      Eve   13     B
5     Jack   16     C
6      Tom   15     A
7     Emma   15     A

# **데이터프레임 크기**
* 데이터프레임의 행과 열 개수를 튜플 형태로 변환

In [46]:
#데이터프레임 크기 확인
print('Shape :',df.shape)
df.shape

Shape : (8, 3)

(8, 3)

모든 열 이름

In [45]:
# 열 이름 확인하기
print("Columns :",df.columns)
df.columns

Columns : Index(['name', 'age', 'grade'], dtype='object')

Index(['name', 'age', 'grade'], dtype='object')

# **열의 데이터 타입**
* 숫자 , 문자열 , 날짜 등 데이터의 종류 파악

In [39]:
# 각 열의 데이터 타입 확인
print("Data Type :", df.dtypes)

Data Type : name     object
age       int64
grade    object
dtype: object

# **데이터프레임 정보**
* 각 열의 데이터 타입
* null값 개수
* 메모리 사용량

In [48]:
#데이터프레임 요약 정보 확인
print("DataFrame Info :",df.info)

DataFrame Info : <bound method DataFrame.info of       name  age grade
0    Alice   14     A
1      Bob   13     B
2  Charlie   15     A
3    Diana   14     C
4      Eve   13     B
5     Jack   16     C
6      Tom   15     A
7     Emma   15     A>

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   age     8 non-null      int64
 2   grade   8 non-null      object
dtypes: int64(1), object(2)
memory usage: 320.0+ bytes

# **수치형 열의 요약 통계**
* 기본 통계 정보 : 평균 , 표준편차 , 최소/최대값, 사분위수 등

In [50]:
# 수치형 열의 요약 통계 확인
print("Summary Staristics :")
df.describe()

Summary Staristics :

            age
count   8.00000
mean   14.37500
std     1.06066
min    13.00000
25%    13.75000
50%    14.50000
75%    15.00000
max    16.00000

# **특정 열의 고유값 개수 세기**
* 예를 들어, grade 열에서 각 등급이 몇 번 나타나는지

In [51]:
# 특정 열에서 고유값 개수 세기 grade.ver
print("Grade Counts :")
df['grade'].value_counts()

Grade Counts :

grade
A    4
B    2
C    2
Name: count, dtype: int64

In [53]:
# 특정 열에서 고유값 개수 세기 age.ver
print("Age Counts :")
df['age'].value_counts()

Age Counts :

age
15    3
14    2
13    2
16    1
Name: count, dtype: int64

In [54]:
# grade columns의 고유값 확인
print("Unique Grades :")
df['grade'].unique()

Unique Grades :

array(['A', 'B', 'C'], dtype=object)

In [55]:
# grade columns의 고유값 확인
print("Unique Grades :")
print(df['grade'].unique())

Unique Grades :
['A' 'B' 'C']

데이터프레임에서 랜덤 샘플 추출-무작위로 샘플 행을 추출하여 데이터를 빠르게 확인

In [56]:
# 무작위로 3개의 행 추출 3개.ver
print("Random sample :")
df.sample(3)

Random sample :

    name  age grade
6    Tom   15     A
3  Diana   14     C
4    Eve   13     B

In [57]:
# 무작위로 3개의 행 추출 5개.ver
print("Random sample :")
df.sample(5)

Random sample :

      name  age grade
0    Alice   14     A
5     Jack   16     C
2  Charlie   15     A
6      Tom   15     A
1      Bob   13     B

# **결측값 확인**

In [58]:
# 결측값이 있는지 확인
print('Null Values :')
df.isnull()

Null Values :

    name    age  grade
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False

In [59]:
#  결측값이 있는지 확인 column별로
print("Null Values Count by Column :")
df.isnull().sum()

Null Values Count by Column :

name     0
age      0
grade    0
dtype: int64

# **인덱싱과 슬라이싱**
* 열 이름으로 선택 : df['열 이름']

**(1) . 기본 인덱싱 (열 선택)**

In [61]:
# 특정 열 선택
df['name'] #name만 선택
df[['name','grade']] # name과 grade를 선택

      name grade
0    Alice     A
1      Bob     B
2  Charlie     A
3    Diana     C
4      Eve     B
5     Jack     C
6      Tom     A
7     Emma     A

**(2). 라벨(이름) 기반 인덱싱**

In [63]:
# 특정 행 선택 (index 0)
df.loc[0]

name     Alice
age         14
grade        A
Name: 0, dtype: object

In [65]:
# 특정 행과 열 선택
df.loc[0,'name']

'Alice'

In [67]:
df.loc[0:2 , ['name','age']] # 첫번째 행부터 세번째까지 name과 age 열 선택

      name  age
0    Alice   14
1      Bob   13
2  Charlie   15

**(3). 위치(숫자) 기반 인덱싱**

In [68]:
# 첫번째 행 선택 (위치 o)
df.iloc[0]

name     Alice
age         14
grade        A
Name: 0, dtype: object

In [69]:
# 특정 위치의 행과 열 선택
df.iloc[0,1]

14

In [70]:
# 여러 행과 열 선택
df.iloc[0:2 , 0:2]

    name  age
0  Alice   14
1    Bob   13