In [ ]:
import pandas as pd

In [ ]:
data = [100,290,80]
sr = pd.Series(data)
sr

0    100
1    290
2     80
dtype: int64

In [ ]:
data = [100,290,80]
sr = pd.Series(data)
sr.index = ['소울좌','오페라좌','혼미좌']
sr

소울좌     100
오페라좌    290
혼미좌      80
dtype: int64

In [ ]:
data = [100,290,80]
sr = pd.Series(data,index=['소울좌','오페라좌','혼미좌'])
sr

소울좌     100
오페라좌    290
혼미좌      80
dtype: int64

In [ ]:
data = [[100,'여',True],
        [90,'남',True],
        [80,'남',False]]

df = pd.DataFrame(data)
df

     0  1     2
0  100  여  True
1   90  남  True
2   80  남  True

In [ ]:
data = [[100,'여',1,True],
        [90,'남',2,True],
        [80,'남',3,False]]

df = pd.DataFrame(data)
df.index = ['소울좌','오페라좌','혼미좌']
df.columns = ['점수','성별','등수','성공']
df

       점수 성별  등수     성공
소울좌   100  여   1   True
오페라좌   90  남   2   True
혼미좌    80  남   3  False

In [ ]:
data = [[100,'여',1,True],
        [90,'남',2,True],
        [80,'남',3,False]]

df = pd.DataFrame(data,index = ['소울좌','오페라좌','혼미좌'])
df

        0  1  2      3
소울좌   100  여  1   True
오페라좌   90  남  2   True
혼미좌    80  남  3  False

In [ ]:
data = [[100,'여',1,True],
        [90,'남',2,True],
        [80,'남',3,False]]

df = pd.DataFrame(data,columns = ['점수','성별','등수','성공'])
df

    점수 성별  등수     성공
0  100  여   1   True
1   90  남   2   True
2   80  남   3  False

In [ ]:
data = [[100,'여',1,True],
        [90,'남',2,True],
        [80,'남',3,False]]

df = pd.DataFrame(data)
df.index = ['소울좌','오페라좌','혼미좌']
df.columns = ['점수','성별','등수','성공']
df['점수']

소울좌     여
오페라좌    남
혼미좌     남
Name: 성별, dtype: object

In [ ]:
df['성별']

소울좌     여
오페라좌    남
혼미좌     남
Name: 성별, dtype: object

In [ ]:
df['등수']

소울좌     1
오페라좌    2
혼미좌     3
Name: 등수, dtype: int64

In [ ]:
df['성공']

소울좌      True
오페라좌     True
혼미좌     False
Name: 성공, dtype: bool

In [ ]:
print(df.loc['소울좌'])

점수     100
성별       여
등수       1
성공    True
Name: 소울좌, dtype: object

In [ ]:
df[['점수','등수']]

       점수  등수
소울좌   100   1
오페라좌   90   2
혼미좌    80   3

In [ ]:
print(df.loc[['소울좌','혼미좌']])

      점수 성별  등수     성공
소울좌  100  여   1   True
혼미좌   80  남   3  False

In [ ]:
df.loc[['오페라좌','혼미좌']]

      점수 성별  등수     성공
오페라좌  90  남   2   True
혼미좌   80  남   3  False

In [ ]:
df[['성별','등수']]

     성별  등수
소울좌   여   1
오페라좌  남   2
혼미좌   남   3

In [ ]:
data={'송가인':100,'임영웅':90,'영탁':80}
sr = pd.Series(data)
sr

송가인    100
임영웅     90
영탁      80
dtype: int64

In [ ]:
sr[0] , sr['송가인']

<ipython-input-33-d8e5a20ae091>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr[0] , sr['송가인']

(100, 100)

In [ ]:
data = [100,90,80]
sr = pd.Series(data,index=['송가인','임영웅','영탁'])
sr

송가인    100
임영웅     90
영탁      80
dtype: int64

In [ ]:
data = (100,90,80)
sr = pd.Series(data,index=['송가인','임영웅','영탁'])
sr

송가인    100
임영웅     90
영탁      80
dtype: int64

In [ ]:
data = (100,90,80)
sr = pd.Series(data,index=['송가인','임영웅','영탁'])
sr

송가인    100
임영웅     90
영탁      80
dtype: int64

In [ ]:
sr[[1,2]]

<ipython-input-43-212cb2841e12>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr[[1,2]]

임영웅    90
영탁     80
dtype: int64

In [ ]:
print(sr[2],sr['영탁'])

80 80

<ipython-input-45-f36e7bd601d3>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr[2],sr['영탁'])

In [ ]:
data={
    '점수':[100,90,80],
    '성별':['여','남','남'],
    '등수':[1,2,3],
    '상금':[True,False,False]

}

df = pd.DataFrame(data)
df

    점수 성별  등수     상금
0  100  여   1   True
1   90  남   2  False
2   80  남   3  False

In [ ]:
df.index=['송가인','임영운','영탁']
df

      점수 성별  등수     상금
송가인  100  여   1   True
임영운   90  남   2  False
영탁    80  남   3  False