# Pandas 불러오기

In [1]:
# pandas 가져오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import platform

# 한국어 폰트 설정
system = platform.system()
if system == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif system == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'Noto Sans CJK JP'

# 음수 기호 표시
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.dpi'] = 100

# Series (1차원 데이터 구조)

- **Series** : 모든 유형의 데이터를 보유하는 1차원 레이블 배열
- 인덱스(라벨)와 데이터 값으로 구성

In [2]:
# 기본 Series 생성 - 리스트로부터
s1 = pd.Series([1, 3, 5, np.nan, 6, 8])
s1

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
# 인덱스 설정하여 Series 생성
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
s2

a    10
b    20
c    30
d    40
dtype: int64

In [4]:
# 딕셔너리로부터 Series 생성
data = {'과자': 100, '음료': 200, '과일': 150}
s3 = pd.Series(data)
s3

과자    100
음료    200
과일    150
dtype: int64

In [5]:
# Series 인덱싱
print(s2.iloc[0])  # 위치 기반 (명시적)
print(s2['a'])  # 라벨 기반

10
10

In [6]:
# Series 슬라이싱
print(s2[0:2])  # 인덱스로 슬라이싱
print(s2[['a', 'c']])  # 특정 라벨 선택

a    10
b    20
dtype: int64
a    10
c    30
dtype: int64

# DataFrame (2차원 데이터 구조)

- **DataFrame** : 행과 열로 구성된 표나 2차원 배열처럼 데이터를 보관하는 2차원적 데이터 구조
- 여러 Series의 모임

In [7]:
# 딕셔너리로부터 DataFrame 생성
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'Score': [85, 90, 78, 92]
})
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78
3    David   28     92

In [8]:
# .shape : DataFrame의 크기 (행, 열)
df.shape

(4, 3)

In [9]:
# .info() : DataFrame의 정보 조회
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [10]:
# .describe() : 통계 요약
df.describe()

             Age      Score
count   4.000000   4.000000
mean   29.500000  86.250000
std     4.203173   6.238322
min    25.000000  78.000000
25%    27.250000  83.250000
50%    29.000000  87.500000
75%    31.250000  90.500000
max    35.000000  92.000000

In [11]:
# .head() : 처음 n개 행 보기 (기본값 5)
df.head(2)

    Name  Age  Score
0  Alice   25     85
1    Bob   30     90

In [12]:
# .tail() : 마지막 n개 행 보기
df.tail(2)

      Name  Age  Score
2  Charlie   35     78
3    David   28     92

# 데이터 선택 및 필터링

In [13]:
# 열 선택하기
print(df['Name'])  # 단일 열
print()
print(df[['Name', 'Age']])  # 다중 열

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28

In [14]:
# .loc[] : 라벨 기반 인덱싱
print(df.loc[0])  # 첫 번째 행
print()
print(df.loc[0, 'Name'])  # 특정 셀

Name     Alice
Age         25
Score       85
Name: 0, dtype: object

Alice

In [15]:
# .iloc[] : 위치 기반 인덱싱
print(df.iloc[0])  # 첫 번째 행
print()
print(df.iloc[0, 1])  # 첫 번째 행, 두 번째 열

Name     Alice
Age         25
Score       85
Name: 0, dtype: object

25

In [16]:
# 조건으로 필터링
print(df[df['Age'] > 28])  # 나이가 28보다 큰 행

      Name  Age  Score
1      Bob   30     90
2  Charlie   35     78

In [17]:
# 여러 조건으로 필터링
print(df[(df['Age'] > 25) & (df['Score'] >= 85)])

    Name  Age  Score
1    Bob   30     90
3  David   28     92

# 데이터 조작 (Data Manipulation)

In [18]:
# 새로운 열 추가
df['Grade'] = ['A', 'A', 'B', 'A']
df

      Name  Age  Score Grade
0    Alice   25     85     A
1      Bob   30     90     A
2  Charlie   35     78     B
3    David   28     92     A

In [19]:
# 열 삭제
df_drop = df.drop('Grade', axis=1)
df_drop

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78
3    David   28     92

In [20]:
# .rename() : 열 이름 변경
df_renamed = df.rename(columns={'Name': 'Student', 'Age': 'Year'})
df_renamed

   Student  Year  Score Grade
0    Alice    25     85     A
1      Bob    30     90     A
2  Charlie    35     78     B
3    David    28     92     A

In [21]:
# .sort_values() : 정렬
df_sorted = df.sort_values(by='Score', ascending=False)
df_sorted

      Name  Age  Score Grade
3    David   28     92     A
1      Bob   30     90     A
0    Alice   25     85     A
2  Charlie   35     78     B

# 결측값(Missing Data) 처리

In [22]:
# 결측값 포함 DataFrame 생성
df_missing = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [9, 10, 11, 12]
})
df_missing

     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12

In [23]:
# .isnull() / .isna() : 결측값 확인
df_missing.isnull()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False
3  False  False  False

In [24]:
# .dropna() : 결측값 행 제거
df_dropped = df_missing.dropna()
df_dropped

     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

In [25]:
# .fillna() : 결측값 채우기
df_filled = df_missing.fillna(0)
df_filled

     A    B   C
0  1.0  5.0   9
1  2.0  0.0  10
2  0.0  0.0  11
3  4.0  8.0  12

In [26]:
# 평균값으로 결측값 채우기
df_mean = df_missing.fillna(df_missing.mean())
df_mean

          A    B   C
0  1.000000  5.0   9
1  2.000000  6.5  10
2  2.333333  6.5  11
3  4.000000  8.0  12

# 그룹화 (Grouping) 및 집계 (Aggregation)

In [27]:
# 그룹화 데이터 생성
sales_df = pd.DataFrame({
    'Department': ['Sales', 'Sales', 'IT', 'IT', 'HR', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [50000, 55000, 60000, 65000, 45000, 48000]
})
sales_df

  Department Employee  Salary
0      Sales    Alice   50000
1      Sales      Bob   55000
2         IT  Charlie   60000
3         IT    David   65000
4         HR      Eve   45000
5         HR    Frank   48000

In [28]:
# .groupby() : 그룹화
grouped = sales_df.groupby('Department')
grouped.head()

  Department Employee  Salary
0      Sales    Alice   50000
1      Sales      Bob   55000
2         IT  Charlie   60000
3         IT    David   65000
4         HR      Eve   45000
5         HR    Frank   48000

In [29]:
# .sum() : 합계
grouped['Salary'].sum()

Department
HR        93000
IT       125000
Sales    105000
Name: Salary, dtype: int64

In [30]:
# .mean() : 평균
grouped['Salary'].mean()

Department
HR       46500.0
IT       62500.0
Sales    52500.0
Name: Salary, dtype: float64

In [31]:
# .count() : 개수
grouped['Salary'].count()

Department
HR       2
IT       2
Sales    2
Name: Salary, dtype: int64

In [32]:
# .agg() : 여러 집계 함수 동시 적용
grouped['Salary'].agg(['sum', 'mean', 'count', 'min', 'max'])

               sum     mean  count    min    max
Department
HR           93000  46500.0      2  45000  48000
IT          125000  62500.0      2  60000  65000
Sales       105000  52500.0      2  50000  55000

# 데이터 병합 (Merging & Joining)

In [33]:
# 병합할 데이터 생성
df1 = pd.DataFrame({
    'Key': ['A', 'B', 'C'],
    'Value1': [1, 2, 3]
})
df2 = pd.DataFrame({
    'Key': ['A', 'B', 'C'],
    'Value2': [4, 5, 6]
})
df1, df2

(  Key  Value1
 0   A       1
 1   B       2
 2   C       3,
   Key  Value2
 0   A       4
 1   B       5
 2   C       6)

In [34]:
# .merge() : SQL처럼 병합
merged = pd.merge(df1, df2, on='Key')
merged

  Key  Value1  Value2
0   A       1       4
1   B       2       5
2   C       3       6

In [35]:
# .concat() : 연결
df3 = pd.DataFrame({
    'Key': ['D', 'E'],
    'Value1': [4, 5]
})
concatenated = pd.concat([df1, df3], ignore_index=True)
concatenated

  Key  Value1
0   A       1
1   B       2
2   C       3
3   D       4
4   E       5

# 데이터 변환 (Transformation)

In [36]:
# .apply() : 함수 적용
df_nums = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})
df_nums.apply(lambda x: x * 2)

   A   B
0  2   8
1  4  10
2  6  12

In [37]:
# .map() : 요소별 함수 적용 (pandas 2.1.0+에서 applymap은 deprecated)
df_nums.map(lambda x: x ** 2)

   A   B
0  1  16
1  4  25
2  9  36

In [38]:
# .astype() : 데이터 타입 변환
df_types = pd.DataFrame({
    'Age': ['25', '30', '35'],
    'Salary': ['50000', '60000', '70000']
})
df_types['Age'] = df_types['Age'].astype(int)
df_types['Salary'] = df_types['Salary'].astype(int)
df_types.dtypes

Age       int32
Salary    int32
dtype: object

# Pivot 및 Reshape

In [39]:
# Pivot 데이터 생성
pivot_df = pd.DataFrame({
    'Month': ['Jan', 'Jan', 'Feb', 'Feb'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [100, 150, 120, 180]
})
pivot_df

  Month Product  Sales
0   Jan       A    100
1   Jan       B    150
2   Feb       A    120
3   Feb       B    180

In [40]:
# .pivot() : 피벗 테이블
pivot = pivot_df.pivot(index='Month', columns='Product', values='Sales')
pivot

Product    A    B
Month
Feb      120  180
Jan      100  150

In [41]:
# .pivot_table() : 집계 포함 피벗
pivot_agg = pd.pivot_table(pivot_df, values='Sales', index='Month', columns='Product', aggfunc='sum')
pivot_agg

Product    A    B
Month
Feb      120  180
Jan      100  150

In [42]:
# .melt() : 와이드 형식을 롱 형식으로 변환
melted = pd.melt(pivot.reset_index(), id_vars=['Month'], var_name='Product', value_name='Sales')
melted

  Month Product  Sales
0   Feb       A    120
1   Jan       A    100
2   Feb       B    180
3   Jan       B    150

# 파일 입출력 (I/O)

In [43]:
# .to_csv() : CSV 파일로 저장
# df.to_csv('results/data.csv', index=False)

# .read_csv() : CSV 파일 읽기
# df_read = pd.read_csv('data.csv')
print('CSV 파일 저장 및 읽기 예시')

CSV 파일 저장 및 읽기 예시

In [44]:
# .to_excel() : Excel 파일로 저장
# df.to_excel('results/data.xlsx', index=False)

# .read_excel() : Excel 파일 읽기
# df_read = pd.read_excel('data.xlsx')
print('Excel 파일 저장 및 읽기 예시')

Excel 파일 저장 및 읽기 예시

In [45]:
# .to_json() : JSON 파일로 저장
# df.to_json('results/data.json')

# .read_json() : JSON 파일 읽기
# df_read = pd.read_json('data.json')
print('JSON 파일 저장 및 읽기 예시')

JSON 파일 저장 및 읽기 예시

# 통계 함수

In [46]:
# 통계 데이터
stats_df = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [5, 15, 25, 35, 45]
})
stats_df

    A   B
0  10   5
1  20  15
2  30  25
3  40  35
4  50  45

In [47]:
# .mean() : 평균
print('평균:')
print(stats_df.mean())

평균:
A    30.0
B    25.0
dtype: float64

In [48]:
# .std() : 표준편차
print('표준편차:')
print(stats_df.std())

표준편차:
A    15.811388
B    15.811388
dtype: float64

In [49]:
# .min() / .max() : 최소값 / 최대값
print('최소값:')
print(stats_df.min())
print('최대값:')
print(stats_df.max())

최소값:
A    10
B     5
dtype: int64
최대값:
A    50
B    45
dtype: int64

In [50]:
# .corr() : 상관계수
print('상관계수:')
print(stats_df.corr())

상관계수:
     A    B
A  1.0  1.0
B  1.0  1.0

In [51]:
# .cov() : 공분산
print('공분산:')
print(stats_df.cov())

공분산:
       A      B
A  250.0  250.0
B  250.0  250.0